### ISSUE TITLE
Dependencia subyacente con l10n_ar_reports

### ISSUE THREAD

**Issue by Danisan** [odoo-arg/odoo_l10n_ar#6]
Esta dependencia con el modulo Enterprise mencionado, provoca un external_id not found (está buscando un external id del menu l10n_ar.account_reports_ar_statements_menu (que está en el l10n_ar original).

Solución que propongo 1: incorporar un menú con ese external id en el modulo l10n_ar de esta localización para engañar al instalador.
Solución que propongo 2: crear un modulo l10n_ar_reports dentro de la localización que supla al módulo original.
(ojo, este modulo no podría forkearse por la licencia).

**Comment by lbaldi** [comment]
@Danisan  en el script de travis estan los pasos para la correcta instacion. Como hay dos modulos que vienen en el addons base de odoo pertenecientes a localizacion argentina, antes de instalar cualquier modulo debemos eliminarlos "rm -r /home/travis/odoo-10.0/addons/l10n_ar*. Otro camino seria tomar otros nombres para los modulos de la localizacion que se esta armando y no tener conflicto con otra localizacion. 

Se tomo el otro camino dado que no tiene sentido tener dos localizaciones instaladas.

**Comment by lbaldi** [comment]
@Danisan pudiste revisar este punto?
